version: '3.6'
services:
  mongo:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: iamgroot
    ports:
      - '8001:8001'
  
  mongo-express:
    image: 'mongo-express'
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: iamgroot
      ME_CONFIG_MONGODB_URL: mongodb://root:iamgroot@mongo:27017/